name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: |
          docker compose -f docker-compose.yml run --rm app sh -c "python manage.py test"
      - name: Lint
        run: |
          docker compose -f docker-compose.yml run --rm app sh -c "flake8"
